name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies for main app
        run: npm ci
      - name: Check style
        run: npm run eslint
      - name: Hello World
        run: echo "hello world!"
      - name: Building
        run: npm run build
      - name: Install dependencies for the Playwright tests
        run: cd e2e-playwright && npm ci
      - name: Install Playwright Browsers
        run: cd e2e-playwright && npx playwright install --with-deps
      - name: Testing
        run: npm run test:e2e
      
      - name: Create deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          node-version: lts/Jod #optional
          cli-version: 2.2.0 #optional
